name: Run Stock Report Script

on:
  schedule:
    - cron: "30 3 * * *"   # Runs at 03:38 UTC = 09:08 IST  #3:47 AM UTC = 9:17 AM IST OR  3:37 AM UTC = 9:07 AM IST OR 3:45 AM UTC = 9:15 AM IST 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run the script
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python test1.py