name: Run Stock Report Scripts

on:
  schedule:
    - cron: "28 3 * * *"   # Runs at 03:38 UTC = 09:08 IST
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Increase timeout to give scripts enough time

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r Swing_Str2/requirements.txt

      - name: Run test1.py
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          python test1.py > test1.log 2>&1
          if [ $? -ne 0 ]; then
            echo "test1.py failed, see test1.log for details"
            exit 1
          fi

      - name: Run Swing_Str2.py
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          python Swing_Str2/Swing_Str2.py > swing_str2.log 2>&1
          if [ $? -ne 0 ]; then
            echo "Swing_Str2.py failed, see swing_str2.log for details"
            exit 1
          fi

      - name: Upload logs (if any)
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: script-logs
          path: |
            test1.log
            swing_str2.log

      - name: Clean up
        run: rm -f test1.log swing_str2.log